# Generated by Django 3.2.4 on 2021-06-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_posted',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Todo', max_length=60),
        ),
        migrations.AddField(
            model_name='todo',
            name='titel',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
