# Generated by Django 3.2.4 on 2021-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210630_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='titel',
        ),
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
