# Generated by Django 3.2.5 on 2021-07-04 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 21, 48, 47, 163983), verbose_name='date posted'),
        ),
    ]
