# Generated by Django 3.2.6 on 2021-08-05 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 5, 21, 50, 9, 124146)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
