# Generated by Django 3.2.5 on 2021-07-07 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 20, 43, 5, 537498), verbose_name='date posted'),
        ),
    ]
