# Generated by Django 3.2.5 on 2021-07-08 02:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_todo_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 8, 2, 1, 41, 101711)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
