# Generated by Django 3.2.5 on 2021-07-08 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210708_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 8, 2, 11, 57, 891380)),
        ),
    ]
