# Generated by Django 3.2.6 on 2021-08-05 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_todo_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 5, 21, 21, 34, 477192)),
        ),
    ]
